### PR TITLE
Create SubscribeForm.php

### PR DESCRIPTION
**Pull request by sandykurniawan19**

### CODE REVIEW

**Comment by napolux** [comment]
What's this @sandykurniawan19 ?

**Comment by sandykurniawan19** [comment]
to add a display to provide service delivery of a message to a user @napolux #3

**Comment by sandykurniawan19** [comment]
i think your project same with https://github.com/zhiephie/boilerplate-slim3/tree/master/components ,

**Comment by napolux** [comment]
Closing. Implementation doesn't look complete.

**Comment by sandykurniawan19** [comment]
not complete? why? @napolux

**Pull request closed without merging**
